apiVersion: v1
kind: Service
metadata:
  name: devices
spec:
  type: NodePort
  selector:
    app: devices
  ports:
    - protocol: TCP
      name: "5001"
      port: 5001
      targetPort: 5000
      nodePort: 30001