apiVersion: v1
kind: Service
metadata:
  name: telemetry
spec:
  type: NodePort
  selector:
    app: telemetry
  ports:
    - protocol: TCP
      name: "9092"
      port: 9092
      targetPort: 9092
      nodePort: 30002
