apiVersion: v1
kind: Service
metadata:
  name: smarthome
spec:
  type: NodePort
  selector:
    app: smarthome
  ports:
    - protocol: TCP
      name: "8081"
      port: 8081
      targetPort: 8080
      nodePort: 30003

