apiVersion: v1
kind: Service
metadata:
  name: telemetry
spec:
  type: NodePort
  selector:
    app: telemetry
  ports:
    - protocol: TCP
      name: "5002"
      port: 5002
      targetPort: 5001
      nodePort: 30004

